### PR TITLE
Update .travis.yml for apple-clang 8.1

### PR DESCRIPTION
**Pull request by half2me**

### CODE REVIEW

**Comment by lasote** [comment]
Hi, I've updated the travis.yml file, currently only these versions are available:

```
       - os: osx
         osx_image: xcode8.2 # apple-clang 8.0
         language: generic
         env:
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env:
       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
         env:
```

**Comment by half2me** [comment]
@lasote xcode8.1 was working for me

**Comment by lasote** [comment]
@half2me yes, but it comes with clang 8.0 too, so you will be generating the same packages. 
I'm adding the new xcode8.3 with clang 8.1

**Comment by half2me** [comment]
@lasote I see, thanks :) 👍

**Pull request closed without merging**
